export const CYCLE_STAGE = {
  GOAL_SETTING: 'GOAL_SETTING',
  GROWTH_CONNECT_1: 'GROWTH_CONNECT_1',
  GROWTH_CONNECT_2: 'GROWTH_CONNECT_2',
  GROWTH_CONNECT_3: 'GROWTH_CONNECT_3',
  YEAR_END: 'YEAR_END',
  MANAGER_ASSESSMENT: 'MANAGER_ASSESSMENT',
  DISCUSSION: 'DISCUSSION',
  CALIBRATION: 'CALIBRATION',
  FINAL_OUTCOME: 'FINAL_OUTCOME',
} as const;

export type CycleStageKey = (typeof CYCLE_STAGE)[keyof typeof CYCLE_STAGE];

export const CYCLE_STAGE_LABELS: Record<CycleStageKey, string> = {
  [CYCLE_STAGE.GOAL_SETTING]: 'Goal Setting',
  [CYCLE_STAGE.GROWTH_CONNECT_1]: 'Growth Connect Q1',
  [CYCLE_STAGE.GROWTH_CONNECT_2]: 'Growth Connect Q2',
  [CYCLE_STAGE.GROWTH_CONNECT_3]: 'Growth Connect Q3',
  [CYCLE_STAGE.YEAR_END]: 'Year-End Self Appraisal',
  [CYCLE_STAGE.MANAGER_ASSESSMENT]: 'Manager Assessment',
  [CYCLE_STAGE.DISCUSSION]: 'Performance & Growth Discussion',
  [CYCLE_STAGE.CALIBRATION]: 'Calibration',
  [CYCLE_STAGE.FINAL_OUTCOME]: 'Final Outcome',
};

export const CYCLE_STAGE_ORDER: CycleStageKey[] = [
  CYCLE_STAGE.GOAL_SETTING,
  CYCLE_STAGE.GROWTH_CONNECT_1,
  CYCLE_STAGE.GROWTH_CONNECT_2,
  CYCLE_STAGE.GROWTH_CONNECT_3,
  CYCLE_STAGE.YEAR_END,
  CYCLE_STAGE.MANAGER_ASSESSMENT,
  CYCLE_STAGE.DISCUSSION,
  CYCLE_STAGE.CALIBRATION,
  CYCLE_STAGE.FINAL_OUTCOME,
];
