export const FINAL_RATING = {
  EXCEPTIONAL: 'EXCEPTIONAL',
  EXCEEDS_EXPECTATIONS: 'EXCEEDS_EXPECTATIONS',
  MEETS_EXPECTATIONS: 'MEETS_EXPECTATIONS',
  NEEDS_IMPROVEMENT: 'NEEDS_IMPROVEMENT',
  UNSATISFACTORY: 'UNSATISFACTORY',
} as const;

export type FinalRatingKey = (typeof FINAL_RATING)[keyof typeof FINAL_RATING];

export const FINAL_RATING_LABELS: Record<FinalRatingKey, string> = {
  [FINAL_RATING.EXCEPTIONAL]: 'Exceptional',
  [FINAL_RATING.EXCEEDS_EXPECTATIONS]: 'Exceeds Expectations',
  [FINAL_RATING.MEETS_EXPECTATIONS]: 'Meets Expectations',
  [FINAL_RATING.NEEDS_IMPROVEMENT]: 'Needs Improvement',
  [FINAL_RATING.UNSATISFACTORY]: 'Unsatisfactory',
};

export const FINAL_RATING_ORDER: FinalRatingKey[] = [
  FINAL_RATING.EXCEPTIONAL,
  FINAL_RATING.EXCEEDS_EXPECTATIONS,
  FINAL_RATING.MEETS_EXPECTATIONS,
  FINAL_RATING.NEEDS_IMPROVEMENT,
  FINAL_RATING.UNSATISFACTORY,
];
