export const REVISION_REASON = {
  BUSINESS_PRIORITY_CHANGED: 'BUSINESS_PRIORITY_CHANGED',
  PROJECT_CHANGED: 'PROJECT_CHANGED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  GOAL_ALREADY_ACHIEVED: 'GOAL_ALREADY_ACHIEVED',
  NEW_RESPONSIBILITY_ASSIGNED: 'NEW_RESPONSIBILITY_ASSIGNED',
  OTHER: 'OTHER',
} as const;

export type RevisionReasonKey = (typeof REVISION_REASON)[keyof typeof REVISION_REASON];

export const REVISION_REASON_LABELS: Record<RevisionReasonKey, string> = {
  [REVISION_REASON.BUSINESS_PRIORITY_CHANGED]: 'Business Priority Changed',
  [REVISION_REASON.PROJECT_CHANGED]: 'Project Changed',
  [REVISION_REASON.ROLE_CHANGED]: 'Role Changed',
  [REVISION_REASON.GOAL_ALREADY_ACHIEVED]: 'Goal Already Achieved',
  [REVISION_REASON.NEW_RESPONSIBILITY_ASSIGNED]: 'New Responsibility Assigned',
  [REVISION_REASON.OTHER]: 'Other',
};
